name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Testing on node.js v${{ matrix.node }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Install npm dependencies
      run: yarn
    - name: create .env file
      run: |
        touch .env
        echo REDIS_URL=${{ secrets.REDIS_URL }} >> .env
    - name: Run tests
      run: yarn test

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: create .env file
      run: |
        touch .env
        echo REDIS_URL=${{ secrets.REDIS_URL }} >> .env
    - name: Install npm dependencies
      run: yarn
    - name: Run lint
      run: yarn lint
    - name: Run coverage
      run: yarn test --coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
